#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Demo;


namespace Demo	
{
	public partial class AdventureWorks : OpenAccessContext, IAdventureWorksUnitOfWork
	{
		private static string connectionStringName = @"AdventureWorks2012Connection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
		
			
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("AdventureWorks.rlinq");
	
		public AdventureWorks()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public AdventureWorks(string connection)
			:base(connection, backend, metadataSource)
		{ }
	
		public AdventureWorks(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public AdventureWorks(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public AdventureWorks(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<SalesDetail> SalesDetails 
		{
	    	get
	    	{
	        	return this.GetAll<SalesDetail>();
	    	}
		}
		
		public IQueryable<SalesSummary> SalesSummaries 
		{
	    	get
	    	{
	        	return this.GetAll<SalesSummary>();
	    	}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MsSql";
			backend.ProviderName = "System.Data.SqlClient";
			return backend;
		}
	}

	public interface IAdventureWorksUnitOfWork : IUnitOfWork
	{
		IQueryable<SalesDetail> SalesDetails 
		{ 
			get;
		}

		IQueryable<SalesSummary> SalesSummaries 
		{ 
			get;
		}

	}
}
#pragma warning restore 1591

