#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;


namespace Demo	
{
	public partial class SalesSummary
	{
		private decimal _subTotal;
		public virtual decimal SubTotal 
		{ 
		    get
		    {
		        return this._subTotal;
		    }
		    set
		    {
		        this._subTotal = value;
		    }
		}
		
		private string _salesTerritory;
		public virtual string SalesTerritory 
		{ 
		    get
		    {
		        return this._salesTerritory;
		    }
		    set
		    {
		        this._salesTerritory = value;
		    }
		}
		
		private string _salesPerson;
		public virtual string SalesPerson 
		{ 
		    get
		    {
		        return this._salesPerson;
		    }
		    set
		    {
		        this._salesPerson = value;
		    }
		}
		
		private int _salesOrderID;
		public virtual int SalesOrderID 
		{ 
		    get
		    {
		        return this._salesOrderID;
		    }
		    set
		    {
		        this._salesOrderID = value;
		    }
		}
		
		private string _salesGroup;
		public virtual string SalesGroup 
		{ 
		    get
		    {
		        return this._salesGroup;
		    }
		    set
		    {
		        this._salesGroup = value;
		    }
		}
		
		private string _salesCountry;
		public virtual string SalesCountry 
		{ 
		    get
		    {
		        return this._salesCountry;
		    }
		    set
		    {
		        this._salesCountry = value;
		    }
		}
		
		private DateTime _orderDate;
		public virtual DateTime OrderDate 
		{ 
		    get
		    {
		        return this._orderDate;
		    }
		    set
		    {
		        this._orderDate = value;
		    }
		}
		
		private int? _totalQty;
		public virtual int? TotalQty 
		{ 
		    get
		    {
		        return this._totalQty;
		    }
		    set
		    {
		        this._totalQty = value;
		    }
		}
		
		private int _territoryID;
		public virtual int TerritoryID 
		{ 
		    get
		    {
		        return this._territoryID;
		    }
		    set
		    {
		        this._territoryID = value;
		    }
		}
		
	}
}
