#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;


namespace Demo	
{
	public partial class SalesDetail
	{
		private short _orderQty;
		public virtual short OrderQty 
		{ 
		    get
		    {
		        return this._orderQty;
		    }
		    set
		    {
		        this._orderQty = value;
		    }
		}
		
		private string _salesPerson;
		public virtual string SalesPerson 
		{ 
		    get
		    {
		        return this._salesPerson;
		    }
		    set
		    {
		        this._salesPerson = value;
		    }
		}
		
		private int _specialOfferID;
		public virtual int SpecialOfferID 
		{ 
		    get
		    {
		        return this._specialOfferID;
		    }
		    set
		    {
		        this._specialOfferID = value;
		    }
		}
		
		private decimal _unitPrice;
		public virtual decimal UnitPrice 
		{ 
		    get
		    {
		        return this._unitPrice;
		    }
		    set
		    {
		        this._unitPrice = value;
		    }
		}
		
		private decimal _lineTotal;
		public virtual decimal LineTotal 
		{ 
		    get
		    {
		        return this._lineTotal;
		    }
		    set
		    {
		        this._lineTotal = value;
		    }
		}
		
		private string _salesTerritory;
		public virtual string SalesTerritory 
		{ 
		    get
		    {
		        return this._salesTerritory;
		    }
		    set
		    {
		        this._salesTerritory = value;
		    }
		}
		
		private string _salesCountry;
		public virtual string SalesCountry 
		{ 
		    get
		    {
		        return this._salesCountry;
		    }
		    set
		    {
		        this._salesCountry = value;
		    }
		}
		
		private string _salesGroup;
		public virtual string SalesGroup 
		{ 
		    get
		    {
		        return this._salesGroup;
		    }
		    set
		    {
		        this._salesGroup = value;
		    }
		}
		
		private int _salesOrderDetailID;
		public virtual int SalesOrderDetailID 
		{ 
		    get
		    {
		        return this._salesOrderDetailID;
		    }
		    set
		    {
		        this._salesOrderDetailID = value;
		    }
		}
		
		private string _product;
		public virtual string Product 
		{ 
		    get
		    {
		        return this._product;
		    }
		    set
		    {
		        this._product = value;
		    }
		}
		
	}
}
