// Code is generated by Telerik Add OpenAccess Service Wizard
// using WebApiRepositories.tt template

using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Http;
using Telerik.OpenAccess;

namespace Demo
{
	public partial class ProductRepository : OpenAccessBaseRepository<Demo.Product, Demo.gamesModel>
    {
	
    }

}
