<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="GridModelBinding.aspx.cs" Inherits="Demo._7_NewFeatures.GridModelBinding" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">

      <telerik:RadScriptManager runat="server" ID="scriptMgr"></telerik:RadScriptManager>

    <div>
    
      <telerik:RadAjaxPanel runat="server" ID="panel">
        <telerik:RadGrid runat="server" ID="grid" ItemType="Demo.Product" 
          SelectMethod="GetProducts" UpdateMethod="EditProduct"
          DeleteMethod="DeleteProduct" Skin="Telerik" 
          AllowFilteringByColumn="True" CellSpacing="0" 
          GridLines="None" AutoGenerateEditColumn="True"
          AutoGenerateDeleteColumn="True">

        </telerik:RadGrid>

        </telerik:RadAjaxPanel>

    </div>
    </form>
</body>
</html>
